# Generated by Django 4.2.4 on 2023-08-30 07:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nif',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telemovel',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='perfil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Morada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade_morada', models.CharField(choices=[('E', 'Entrega'), ('F', 'Faturação')])),
                ('morada', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('codigo_postal', models.CharField(blank=True, max_length=4)),
                ('ext_codigo_postal', models.CharField(blank=True, max_length=3)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
            options={
                'verbose_name': 'Morada',
                'verbose_name_plural': 'Moradas',
            },
        ),
    ]
