# Generated by Django 4.2.4 on 2023-08-30 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_morada_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
