# Generated by Django 4.2.4 on 2023-08-30 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0004_alter_perfil_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morada',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=4, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='morada',
            name='ext_codigo_postal',
            field=models.CharField(blank=True, max_length=3, verbose_name='Extensão Código Postal'),
        ),
        migrations.AlterField(
            model_name='morada',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='morada',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telemovel',
            field=models.CharField(blank=True, max_length=9, verbose_name='Telemóvel'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
