# Generated by Django 4.2.5 on 2023-09-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_morada_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
