# Generated by Django 4.2.5 on 2023-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_perfil_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='assets/qrcodes/'),
        ),
    ]
