# Generated by Django 4.2.5 on 2023-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_perfil_numero_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='numero_cliente',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Número Cliente'),
        ),
    ]
