# Generated by Django 4.2.5 on 2023-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_perfil_tipo_fidelidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estudante',
            field=models.CharField(blank=True, choices=[('escola_sec_ramada', 'Sim, na Esc. Sec. Ramada'), ('agrup_vasco_santana', 'Sim no Agrup. Vasco Santana'), ('outra_escola', 'Sim, noutra escola'), ('nao', 'Não')], help_text='Se estudante, indique a escola onde estuda.', max_length=50, null=True, verbose_name='Estudante'),
        ),
    ]
