# Generated by Django 4.2.15 on 2024-08-17 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0016_alter_perfil_estudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultima_actividade',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Última Actividade'),
        ),
    ]
