# Generated by Django 4.2.17 on 2025-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0021_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento'),
        ),
    ]
