# Generated by Django 4.2.18 on 2025-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0023_perfil_notificacoes_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='first_login',
            field=models.BooleanField(default=True, verbose_name='Primeiro Login'),
        ),
    ]
