# Generated by Django 4.2.19 on 2025-02-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0026_pushnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNotification',
        ),
    ]
