# Generated by Django 4.2.19 on 2025-02-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0028_notificationall_notificationuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotificationtoken',
            name='user',
        ),
    ]
