# Generated by Django 4.2.19 on 2025-10-18 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0031_alter_pushnotificationtoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='notificationallsent',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationusersent',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationusersent',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationAll',
        ),
        migrations.DeleteModel(
            name='NotificationAllSent',
        ),
        migrations.DeleteModel(
            name='NotificationUser',
        ),
        migrations.DeleteModel(
            name='NotificationUserSent',
        ),
    ]
