# Generated by Django 4.2.27 on 2025-12-31 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0032_notification_remove_notificationallsent_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morada',
            name='finalidade_morada',
        ),
        migrations.AddField(
            model_name='morada',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='morada',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='morada',
            name='purpose',
            field=models.CharField(choices=[('delivery', 'Entrega'), ('billing', 'Faturação')], default='delivery', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morada',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='has_billing_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='has_delivery_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='has_valid_nif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='onboarding_min_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='reset_password_code_str',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de Reset de Password'),
        ),
        migrations.AlterField(
            model_name='morada',
            name='codigo_postal',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='morada',
            name='ext_codigo_postal',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='morada',
            name='morada',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='morada',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='morada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradas', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero_cliente',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True, verbose_name='Número Cliente'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['numero_cliente'], name='perfil_perf_numero__e9a667_idx'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['telemovel'], name='perfil_perf_telemov_41ecdd_idx'),
        ),
        migrations.AddConstraint(
            model_name='morada',
            constraint=models.UniqueConstraint(fields=('usuario', 'purpose'), name='uniq_address_per_user_purpose'),
        ),
    ]
