# Generated by Django 4.2.27 on 2026-01-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0035_verificationcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['expires_at'], name='perfil_veri_expires_2e7081_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['used_at'], name='perfil_veri_used_at_cdbb72_idx'),
        ),
    ]
