# Generated by Django 4.2.27 on 2026-01-08 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0036_verificationcode_perfil_veri_expires_2e7081_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pending Signup',
                'verbose_name_plural': 'Pending Signups',
                'indexes': [models.Index(fields=['email'], name='perfil_pend_email_038983_idx'), models.Index(fields=['created_at'], name='perfil_pend_created_dae49f_idx'), models.Index(fields=['used_at'], name='perfil_pend_used_at_64d33f_idx')],
            },
        ),
    ]
