# Generated by Django 4.2.27 on 2026-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0037_pendingsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='onboarding_required_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
