# Generated by Django 4.2.27 on 2026-01-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0038_perfil_onboarding_required_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='onboarding_min_completed',
            new_name='onboarding_optional_completed',
        ),
    ]
