# Generated by Django 4.2.27 on 2026-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0040_fix_perfil_created_at_timezone_now"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="perfil",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telemovel", ""), _negated=True),
                fields=("telemovel",),
                name="uniq_perfil_telemovel_non_empty",
            ),
        ),
    ]
