# Generated by Django 4.2.19 on 2025-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('review_id', models.CharField(max_length=255, unique=True)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
