# Generated by Django 4.2.19 on 2025-05-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlereview',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
