"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from typing import Any

from celery.schedules import crontab
from django.contrib.messages import constants
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR.parent / 'data' / 'web'

# Caminho específico para o arquivo .env
dotenv_path = BASE_DIR.parent / 'dotenv_files' / '.env'

# Carregar as variáveis de ambiente a partir do arquivo .env especificado
load_dotenv(dotenv_path=dotenv_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.getenv('DEBUG', 0)))

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'restau.apps.RestauConfig',
    'rest_framework_simplejwt',
    'rest_framework',
    "djangoapp.perfil.apps.PerfilConfig",
    'djangoapp.restau',
    'djangoapp.site_setup',
    'djangoapp.fidelidade',
    'djangoapp.senhas',
    'djangoapp.app_version',
    'djangoapp.google_reviews',
    'djangoapp.commerce',
    'crispy_forms',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoapp.project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'djangoapp.site_setup.context_processors.site_setup'
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoapp.project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'change-me'),
        'NAME': os.getenv('POSTGRES_DB', 'change-me'),
        'USER': os.getenv('POSTGRES_USER', 'change-me'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'change-me'),
        'HOST': os.getenv('POSTGRES_HOST', 'change-me'),
        'PORT': os.getenv('POSTGRES_PORT', 'change-me'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt'

TIME_ZONE = 'Europe/Lisbon'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# /data/web/static
STATIC_ROOT = DATA_DIR / 'static'

MEDIA_URL = '/media/'
# /data/web/media
MEDIA_ROOT = DATA_DIR / 'media'


MESSAGE_TAGS = {
    constants.DEBUG: 'alert-info',
    constants.ERROR: 'alert-danger',
    constants.INFO: 'alert-info',
    constants.SUCCESS: 'alert-success',
    constants.WARNING: 'alert-warning',
}

# Sessão em dias: 60s * 60m * 24h * 1d * 3 meses
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30 * 3  

# Salvar a cada requisição
SESSION_SAVE_EVERY_REQUEST = True

# Sessão expira quando o navegador é fechado
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Salvar a sessão em base de dados
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Serializer - Padrão JSON
# SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK: dict[str, Any] = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
        "EXCEPTION_HANDLER": "djangoapp.perfil.api.exception_handler.custom_exception_handler",
}

SIMPLE_JWT: dict[str, Any] = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "SIGNING_KEY": os.getenv('SECRET_KEY_JWT', 'change-me'),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

LOGGING: dict[str, Any] = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

# Email configuration local
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email configuration real
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'change-me')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'change-me')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 'change-me'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'change-me')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'change-me')

def env_bool(key: str, default: bool = False) -> bool:
    v = os.getenv(key)
    if v is None:
        return default
    return v.strip().lower() in ("1", "true", "yes", "on")

EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)


# Frontend URL
FRONTEND_URL = os.getenv('FRONTEND_URL', 'change-me')

# Forçar import explícito de tasks
CELERY_IMPORTS = ('djangoapp.fidelidade.tasks',)

CELERY_BROKER_URL = os.getenv(
    'CELERY_BROKER_URL',
    'redis://redis:6379/0',  # default para Docker
)
CELERY_RESULT_BACKEND = os.getenv(
    'CELERY_RESULT_BACKEND',
    'redis://redis:6379/1',
)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False



CELERY_BEAT_SCHEDULE = {
    'expirar_pontos_inativos_diariamente': {
        'task': 'djangoapp.fidelidade.tasks.expirar_pontos_inativos_task',
        'schedule': crontab(hour=9, minute=0),  # todos os dias às 09:00
        'args': (45,),  # dias de inactividade
    },

    'avisos_aniversario_diarios': {
        'task': 'djangoapp.fidelidade.tasks.enviar_avisos_aniversario_task',
        'schedule': crontab(hour=10, minute=0),  # todos os dias às 10:00
    },

    'avisos_pontos_a_expirar_diarios': {
        'task': 'djangoapp.fidelidade.tasks.enviar_avisos_pontos_a_expirar_task',
        'schedule': crontab(hour=10, minute=5),  # todos os dias às 10:05
    },
}

# Google Cloud Storage configuration

GCS_BUCKET_NAME = os.getenv("GCS_BUCKET_NAME", "change-me")
GCS_PUBLIC_BASE_URL = os.getenv(
    "GCS_PUBLIC_BASE_URL",
    "change-me",
)

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "djangoapp.perfil.auth_backends.IdentifierBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Authentication configuration
# AUTH_USER_MODEL = 'perfil.User'
# LOGIN_URL = 'perfil:login'
# LOGOUT_URL = 'perfil:logout'
# LOGIN_REDIRECT_URL = 'perfil:dashboard'
# LOGOUT_REDIRECT_URL = 'perfil:login'

# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS: list[dict[str, Any]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",     
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]