# Generated by Django 4.2.10 on 2024-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0008_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='head_title',
            field=models.CharField(blank=True, default='Teste', max_length=65),
        ),
    ]
