# Generated by Django 4.2.27 on 2025-12-26 23:55

from django.db import migrations, models
import djangoapp.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0009_sitesetup_head_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[djangoapp.utils.model_validators.validate_png]),
        ),
    ]
