# Generated by Django 4.2.3 on 2023-07-21 18:07

from django.db import migrations, models
import django.db.models.deletion
import utils.model_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentagem de desconto (de 0 a 100)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Percentagem',
                'verbose_name_plural': 'Percentagens',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Produts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(max_length=200)),
                ('descricao_longa', models.TextField()),
                ('preco', models.FloatField(default=0.0, validators=[utils.model_validators.positive_price])),
                ('preco_promo', models.FloatField(default=0.0, validators=[utils.model_validators.positive_price])),
                ('visibilidade', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='assets/Products/', validators=[utils.model_validators.validate_png])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restau.category')),
                ('percentagem_desconto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.percentage')),
                ('subcategoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.subcategory')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
