# Generated by Django 4.2.3 on 2023-07-24 08:29

from django.db import migrations, models
import django.db.models.deletion
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0002_alter_produts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(max_length=200)),
                ('descricao_longa', models.TextField()),
                ('preco', models.FloatField(default=0.0, validators=[utils.model_validators.positive_price])),
                ('preco_promo', models.FloatField(default=0.0, validators=[utils.model_validators.positive_price])),
                ('visibilidade', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='assets/Products/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restau.category')),
                ('percentagem_desconto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.percentage')),
                ('subcategoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.subcategory')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='Produts',
        ),
    ]
