# Generated by Django 4.2.3 on 2023-07-25 14:34

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0003_products_delete_produts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='descricao_curta',
            field=models.CharField(max_length=200, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='products',
            name='descricao_longa',
            field=models.TextField(verbose_name='Descrição Longa'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='assets/Products/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco',
            field=models.FloatField(default=0.0, validators=[utils.model_validators.positive_price], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_promo',
            field=models.FloatField(default=0.0, validators=[utils.model_validators.positive_price], verbose_name='Preço Promocional'),
        ),
    ]
