# Generated by Django 4.2.3 on 2023-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0004_alter_products_descricao_curta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='imagem',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='assets/Products/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='products',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Produto'),
        ),
    ]
