# Generated by Django 4.2.3 on 2023-07-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0005_remove_products_image_products_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='descricao_longa',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descrição Longa'),
        ),
    ]
