# Generated by Django 4.2.3 on 2023-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0006_alter_products_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da configuração', max_length=200, verbose_name='Nome')),
                ('imagem_topo', models.ImageField(blank=True, null=True, upload_to='assets/frontend/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'FrontendSetup',
                'verbose_name_plural': 'FrontendSetup',
            },
        ),
    ]
