# Generated by Django 4.2.4 on 2023-08-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0008_frontendsetup_imagem_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendsetup',
            name='imagem_logo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/frontend/logo', verbose_name='Logo'),
        ),
    ]
