# Generated by Django 4.2.4 on 2023-08-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0009_alter_frontendsetup_imagem_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendsetup',
            name='imagem_logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='frontendsetup',
            name='imagem_topo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/', verbose_name='Imagem'),
        ),
    ]
