# Generated by Django 4.2.4 on 2023-08-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0010_alter_frontendsetup_imagem_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontendsetup',
            options={},
        ),
    ]
