# Generated by Django 4.2.4 on 2023-08-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0011_alter_frontendsetup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='category',
            name='nome',
            field=models.CharField(default='nova_categoria', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.subcategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='nome',
            field=models.CharField(default='nova_subcategoria', max_length=200),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
