# Generated by Django 4.2.4 on 2023-08-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0015_alter_products_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restau.subcategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restau.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='percentagem_desconto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restau.percentage'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restau.subcategory'),
        ),
    ]
