# Generated by Django 4.2.4 on 2023-08-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0016_alter_category_subcategoria_alter_products_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, to='restau.subcategory'),
        ),
    ]
