# Generated by Django 4.2.4 on 2023-08-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0017_remove_category_subcategoria_category_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restau.category'),
        ),
    ]
