# Generated by Django 4.2.4 on 2023-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0018_remove_category_subcategoria_subcategory_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
