# Generated by Django 4.2.5 on 2023-09-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0019_products_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('unidade', models.FloatField(default=0.0, verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Fidelização',
                'verbose_name_plural': 'Fidelizações',
            },
        ),
        migrations.CreateModel(
            name='ProdutosFidelizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_recompensa', models.FloatField(default=0.0, verbose_name='Unidades Recompensa')),
                ('produto_fidelizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restau.products')),
            ],
            options={
                'verbose_name': 'Produto Fidelização',
                'verbose_name_plural': 'Produtos Fidelizações',
            },
        ),
    ]
