# Generated by Django 4.2.5 on 2023-09-08 21:33

from django.db import migrations, models
import django.db.models.deletion
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0020_fidelizacao_produtosfidelizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosfidelizacao',
            name='fidelizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restau.fidelizacao'),
        ),
        migrations.AddField(
            model_name='produtosfidelizacao',
            name='pontos_para_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fidelizacao',
            name='unidade',
            field=models.FloatField(default=0.0, verbose_name='Unidade para Euro'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[utils.model_validators.positive_price], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produtosfidelizacao',
            name='produto_fidelizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_fidelizacao', to='restau.products'),
        ),
        migrations.AlterField(
            model_name='produtosfidelizacao',
            name='unidades_recompensa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_recompensa', to='restau.products'),
        ),
    ]
