# Generated by Django 4.2.5 on 2023-09-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0023_remove_produtosfidelizacao_ponotos_recompensa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosfidelizacao',
            name='produto_fidelizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_fidelizacao', to='restau.products', unique=True),
        ),
    ]
