# Generated by Django 4.2.5 on 2023-09-11 09:13

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0024_alter_produtosfidelizacao_produto_fidelizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='preco',
        ),
        migrations.AddField(
            model_name='products',
            name='preco_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='products',
            name='preco_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='products',
            name='preco_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='products',
            name='preco_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='products',
            name='preco_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='products',
            name='preco_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço'),
        ),
    ]
