# Generated by Django 4.2.5 on 2023-09-11 10:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0025_remove_products_preco_products_preco_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Ementa')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('nome_campo_preco_selecionado', models.CharField(choices=[('preco_1', 'Preço 1'), ('preco_2', 'Preço 2'), ('preco_3', 'Preço 3'), ('preco_4', 'Preço 4'), ('preco_5', 'Preço 5'), ('preco_6', 'Preço 6')], max_length=10, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Ementa',
                'verbose_name_plural': 'Ementas',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço 4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço 5'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[utils.model_validators.positive_price], verbose_name='Preço 6'),
        ),
        migrations.CreateModel(
            name='ProdutosEmenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ementa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_ementa', to='restau.ementa', verbose_name='Ementa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_ementa', to='restau.products', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto Ementa',
                'verbose_name_plural': 'Produtos Ementas',
            },
        ),
    ]
