# Generated by Django 4.2.5 on 2023-09-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0027_alter_produtosfidelizacao_produto_fidelizacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produtosementa',
            unique_together={('ementa', 'produto')},
        ),
    ]
