# Generated by Django 4.2.5 on 2023-09-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0029_alter_produtosementa_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ementa',
            name='produtos',
            field=models.ManyToManyField(to='restau.products'),
        ),
    ]
