# Generated by Django 4.2.5 on 2023-09-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0030_ementa_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosfidelizacao',
            name='fidelizacao',
        ),
        migrations.RemoveField(
            model_name='produtosfidelizacao',
            name='pontos_recompensa',
        ),
        migrations.RemoveField(
            model_name='produtosfidelizacao',
            name='produto_fidelizacao',
        ),
        migrations.DeleteModel(
            name='Fidelizacao',
        ),
        migrations.DeleteModel(
            name='ProdutosFidelizacao',
        ),
    ]
