# Generated by Django 4.2.6 on 2023-10-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0031_remove_produtosfidelizacao_fidelizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsetup',
            name='ementa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restau.ementa'),
        ),
    ]
