# Generated by Django 4.2.6 on 2023-10-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0032_frontendsetup_ementa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da foto', max_length=200, verbose_name='Nome')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/galeria', verbose_name='Imagem')),
                ('is_visible', models.BooleanField(default=False, help_text='Visibilidade da foto', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
