# Generated by Django 4.2.6 on 2023-10-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0033_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsetup',
            name='intro',
            field=models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='Introdução'),
        ),
        migrations.AddField(
            model_name='frontendsetup',
            name='intro_imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/forntendsetup/', verbose_name='Imagem intro'),
        ),
    ]
