# Generated by Django 4.2.6 on 2023-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0035_frontendsetup_frase_inspiradora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_logo', models.BooleanField(default=False, help_text='Visibilidade imagem_logo', verbose_name='Logo')),
                ('imagem_topo', models.BooleanField(default=False, help_text='Visibilidade imagem_topo', verbose_name='Imagem')),
                ('intro', models.BooleanField(default=False, help_text='Visibilidade introdução', verbose_name='Introdução')),
                ('intro_imagem', models.BooleanField(default=False, help_text='Visibilidade da imagem intro', verbose_name='Imagem intro')),
                ('frase_inspiradora', models.BooleanField(default=False, help_text='Visibilidade frase inspiradora', verbose_name='Frase inspiradora')),
                ('ementa', models.BooleanField(default=False, help_text='Visibilidade ementa', verbose_name='Ementa')),
                ('imagem_frase_cima', models.BooleanField(default=False, help_text='Visibilidade imagem frase cima', verbose_name='Imagem frase cima')),
                ('imagem_frase_baixo', models.BooleanField(default=False, help_text='Visibilidade imagem frase baixo', verbose_name='Imagem frase baixo')),
                ('imagem_padrao', models.BooleanField(default=False, help_text='Visibilidade imagem padrão', verbose_name='Imagem Padrão')),
            ],
        ),
    ]
