# Generated by Django 4.2.6 on 2023-10-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0036_activesetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesetup',
            name='ementa',
        ),
        migrations.RemoveField(
            model_name='activesetup',
            name='frase_inspiradora',
        ),
        migrations.RemoveField(
            model_name='activesetup',
            name='imagem_frase_baixo',
        ),
        migrations.RemoveField(
            model_name='activesetup',
            name='imagem_frase_cima',
        ),
        migrations.RemoveField(
            model_name='activesetup',
            name='imagem_logo',
        ),
        migrations.RemoveField(
            model_name='activesetup',
            name='imagem_padrao',
        ),
        migrations.RemoveField(
            model_name='activesetup',
            name='imagem_topo',
        ),
        migrations.RemoveField(
            model_name='activesetup',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='activesetup',
            name='intro_imagem',
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_ementa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_ementa_set', to='restau.frontendsetup'),
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_frase_inspiradora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_frase_inspiradora_set', to='restau.frontendsetup'),
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_imagem_frase_baixo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_frase_baixo_set', to='restau.frontendsetup'),
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_imagem_frase_cima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_frase_cima_set', to='restau.frontendsetup'),
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_imagem_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_logo_set', to='restau.frontendsetup'),
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_imagem_padrao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_padrao_set', to='restau.frontendsetup'),
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_imagem_topo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_topo_set', to='restau.frontendsetup'),
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_intro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_intro_set', to='restau.frontendsetup'),
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_intro_imagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_intro_imagem_set', to='restau.frontendsetup'),
        ),
    ]
