# Generated by Django 4.2.6 on 2023-10-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0038_activesetup_active_frase_baixo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da foto', max_length=200, verbose_name='Nome'),
        ),
    ]
