# Generated by Django 4.2.6 on 2023-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0039_alter_fotos_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='ordem',
            field=models.IntegerField(blank=True, default=0, help_text='Ordem da foto na galeria', null=True, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Visibilidade da foto', verbose_name='Visibilidade'),
        ),
    ]
