# Generated by Django 4.2.6 on 2023-10-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0040_fotos_ordem_alter_fotos_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseBaixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Frase Baixo')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da frase baixo.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Frase Baixo',
                'verbose_name_plural': 'Frases Baixo',
            },
        ),
        migrations.CreateModel(
            name='FraseCima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Frase Cima')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da frase cima.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Frase Cima',
                'verbose_name_plural': 'Frases Cima',
            },
        ),
        migrations.CreateModel(
            name='FraseInspiradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Frase Inspiradora')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da frase inspiradora.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Frase Inspiradora',
                'verbose_name_plural': 'Frases Inspiradoras',
            },
        ),
        migrations.CreateModel(
            name='ImagemFraseBaixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/imagem_frase_baixo', verbose_name='Imagem Frase Baixo')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da imagem.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Imagem Frase Baixo',
                'verbose_name_plural': 'Imagens Frases Baixo',
            },
        ),
        migrations.CreateModel(
            name='ImagemFraseCima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/imagem_frase_cima', verbose_name='Imagem Frase Cima')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da imagem.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Imagem Frase Cima',
                'verbose_name_plural': 'Imagens Frases Cima',
            },
        ),
        migrations.CreateModel(
            name='ImagemLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/imagem_logo', verbose_name='Imagem do logo')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade do logo.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Imagem Logo',
                'verbose_name_plural': 'Imagens Logo',
            },
        ),
        migrations.CreateModel(
            name='ImagemPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='assets/frontend/imagem_padrao', verbose_name='Imagem Padrão')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da imagem.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Imagem Padrão',
                'verbose_name_plural': 'Imagens Padrão',
            },
        ),
        migrations.CreateModel(
            name='ImagemTopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/imagem_topo', verbose_name='Imagem Topo')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da imagem.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Imagem Topo',
                'verbose_name_plural': 'Imagens Topo',
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='Texto da intro')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da intro.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Intro',
                'verbose_name_plural': 'Intros',
            },
        ),
        migrations.CreateModel(
            name='IntroImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='assets/frontend/intro_imagem', verbose_name='Imagem da intro')),
                ('is_visible', models.BooleanField(default=True, help_text='Visibilidade da imagem.', verbose_name='Visibilidade')),
            ],
            options={
                'verbose_name': 'Intro Imagem',
                'verbose_name_plural': 'Intros Imagens',
            },
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_ementa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_ementa_set', to='restau.ementa'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_frase_baixo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_frase_baixo_set', to='restau.frasebaixo'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_frase_cima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_frase_cima_set', to='restau.frasecima'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_frase_inspiradora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_frase_inspiradora_set', to='restau.fraseinspiradora'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_frase_baixo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_frase_baixo_set', to='restau.imagemfrasebaixo'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_frase_cima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_frase_cima_set', to='restau.imagemfrasecima'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_logo_set', to='restau.imagemlogo'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_padrao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_padrao_set', to='restau.imagempadrao'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_topo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_topo_set', to='restau.imagemtopo'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_intro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_intro_set', to='restau.intro'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_intro_imagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_intro_imagem_set', to='restau.introimagem'),
        ),
        migrations.DeleteModel(
            name='FrontendSetup',
        ),
    ]
