# Generated by Django 4.2.6 on 2023-10-15 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0041_frasebaixo_frasecima_fraseinspiradora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesetup',
            name='active_ementa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_ementa_set', to='restau.ementa'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_frase_baixo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_frase_baixo_set', to='restau.frasebaixo'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_frase_cima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_frase_cima_set', to='restau.frasecima'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_frase_inspiradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_frase_inspiradora_set', to='restau.fraseinspiradora'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_frase_baixo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_frase_baixo_set', to='restau.imagemfrasebaixo'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_frase_cima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_frase_cima_set', to='restau.imagemfrasecima'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_logo_set', to='restau.imagemlogo'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_padrao_set', to='restau.imagempadrao'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_imagem_topo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_imagem_topo_set', to='restau.imagemtopo'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_intro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_intro_set', to='restau.intro'),
        ),
        migrations.AlterField(
            model_name='activesetup',
            name='active_intro_imagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_intro_imagem_set', to='restau.introimagem'),
        ),
    ]
