# Generated by Django 4.2.6 on 2023-10-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0042_alter_activesetup_active_ementa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemfrasebaixo',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da imagem', max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='imagemfrasecima',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da imagem', max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='imagemlogo',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da imagem', max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='imagempadrao',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da imagem', max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='imagemtopo',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da imagem', max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='introimagem',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da imagem', max_length=200, null=True, verbose_name='Nome'),
        ),
    ]
