# Generated by Django 4.2.6 on 2023-10-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0043_imagemfrasebaixo_nome_imagemfrasecima_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='imagemfrasebaixo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='imagemfrasecima',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='imagemlogo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='imagempadrao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='imagemtopo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='introimagem',
            name='nome',
        ),
    ]
