# Generated by Django 4.2.6 on 2023-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0044_remove_fotos_nome_remove_imagemfrasebaixo_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasebaixo',
            name='texto',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Frase Baixo'),
        ),
        migrations.AlterField(
            model_name='frasecima',
            name='texto',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Frase Cima'),
        ),
        migrations.AlterField(
            model_name='fraseinspiradora',
            name='texto',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Frase Inspiradora'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='texto',
            field=models.TextField(blank=True, default='', max_length=1500, null=True, verbose_name='Texto da intro'),
        ),
    ]
