# Generated by Django 4.2.6 on 2023-10-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0046_contactossite_googlemaps_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia_encerramento',
        ),
        migrations.AddField(
            model_name='activesetup',
            name='active_horario',
            field=models.ManyToManyField(blank=True, related_name='active_horario_set', to='restau.horario'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Encerrado', 'Encerrado')], default='Aberto', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
