# Generated by Django 4.2.6 on 2023-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0047_remove_horario_dia_encerramento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactossite',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contactossite',
            name='facebook_icon',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Facebook Icon'),
        ),
        migrations.AddField(
            model_name='contactossite',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='contactossite',
            name='instagram_icon',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Instagram Icon'),
        ),
        migrations.AlterField(
            model_name='googlemaps',
            name='iframe',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Iframe'),
        ),
    ]
