# Generated by Django 4.2.6 on 2023-10-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0049_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemlogo',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagemlogo',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Visibilidade do logo.', verbose_name='Visibilidade'),
        ),
    ]
