# Generated by Django 4.2.6 on 2023-10-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0050_imagemlogo_checkbox_alter_imagemlogo_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemlogo',
            name='checkbox',
        ),
    ]
