# Generated by Django 4.2.6 on 2023-10-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0052_alter_frasebaixo_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemtopo',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Visibilidade da imagem.', verbose_name='Visibilidade'),
        ),
    ]
