# Generated by Django 4.2.8 on 2023-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0053_alter_imagemtopo_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ementa',
            name='produtos',
            field=models.ManyToManyField(related_name='ementas', to='restau.products'),
        ),
    ]
