# Generated by Django 4.2.9 on 2024-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0054_alter_ementa_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciarVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_versao', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Versão')),
                ('url_download', models.URLField(verbose_name='URL Download')),
                ('notas_versao', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Notas da Versão')),
                ('data_lancamento', models.DateTimeField(verbose_name='Data de Lançamento')),
            ],
            options={
                'verbose_name': 'Gerenciar Versão',
                'verbose_name_plural': 'Gerenciar Versões',
            },
        ),
    ]
