# Generated by Django 4.2.17 on 2025-02-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0056_versaoapp_delete_gerenciarversao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ementa',
            name='produtos',
        ),
    ]
