# Generated by Django 4.2.17 on 2025-02-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0057_remove_ementa_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosementa',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descrição Personalizada'),
        ),
        migrations.AlterField(
            model_name='produtosementa',
            name='ementa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_ementa', to='restau.ementa', verbose_name='Ementa'),
        ),
        migrations.RemoveField(
            model_name='produtosementa',
            name='produto',
        ),
        migrations.AlterField(
            model_name='versaoapp',
            name='numero_versao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Versão'),
        ),
        migrations.AddField(
            model_name='produtosementa',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ementa_produto', to='restau.products', verbose_name='Produto'),
        ),
    ]
