# Generated by Django 4.2.27 on 2025-12-26 23:55

from decimal import Decimal
from django.db import migrations, models
import djangoapp.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0058_produtosementa_descricao_alter_produtosementa_ementa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='preco_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[djangoapp.utils.model_validators.positive_price], verbose_name='Preço 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[djangoapp.utils.model_validators.positive_price], verbose_name='Preço 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[djangoapp.utils.model_validators.positive_price], verbose_name='Preço 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[djangoapp.utils.model_validators.positive_price], verbose_name='Preço 4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[djangoapp.utils.model_validators.positive_price], verbose_name='Preço 5'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[djangoapp.utils.model_validators.positive_price], verbose_name='Preço 6'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preco_promo',
            field=models.FloatField(default=0.0, validators=[djangoapp.utils.model_validators.positive_price], verbose_name='Preço Promocional'),
        ),
    ]
