# Generated by Django 4.2.26 on 2025-12-23 16:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('min_select', models.PositiveIntegerField(default=0)),
                ('max_select', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='AddOnOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='commerce.addongroup')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KitchenPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('network', 'Network'), ('usb', 'USB')], max_length=16)),
                ('host', models.CharField(blank=True, default='', max_length=120)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('usb_vendor_id', models.CharField(blank=True, default='', max_length=32)),
                ('usb_product_id', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('public_code', models.CharField(max_length=32, unique=True)),
                ('source', models.CharField(choices=[('pos', 'POS'), ('mobile', 'Mobile')], default='pos', max_length=16)),
                ('ticket_number', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('kitchen_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='PosDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('device_code', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('is_sellable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDefaultIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_ingredients', to='commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemRemovedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient_name', models.CharField(max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_ingredients', to='commerce.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient_name', models.CharField(max_length=120)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='commerce.orderitem')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.addonoption')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.posdevice'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='commerce.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemRemovedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_ingredients', to='commerce.cartitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='commerce.cartitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.addonoption')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.product'),
        ),
        migrations.AddField(
            model_name='addonoption',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.ingredient'),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='commerce.product'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='commerce.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', '-valid_from'], name='commerce_pr_product_ea3f17_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productdefaultingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='uniq_default_ingredient_per_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitemremovedingredient',
            constraint=models.UniqueConstraint(fields=('item', 'ingredient_name'), name='uniq_order_item_removed_ingredient_name'),
        ),
        migrations.AddConstraint(
            model_name='orderitemaddon',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='order_addon_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitemaddon',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='order_addon_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='order_item_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='ingredientprice',
            index=models.Index(fields=['ingredient', '-valid_from'], name='commerce_in_ingredi_0b3619_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingredientprice',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='ingredient_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cartitemremovedingredient',
            constraint=models.UniqueConstraint(fields=('item', 'ingredient'), name='uniq_cart_item_removed_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='cartitemaddon',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='cart_addon_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='cartitemaddon',
            constraint=models.UniqueConstraint(fields=('item', 'option'), name='uniq_cart_item_addon'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='cart_item_qty_gte_1'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active'], name='commerce_ca_user_id_9c1764_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'is_active'], name='commerce_ca_session_adb149_idx'),
        ),
        migrations.AddConstraint(
            model_name='addonoption',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='addon_option_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='addonoption',
            constraint=models.UniqueConstraint(fields=('group', 'ingredient'), name='uniq_addon_ingredient_per_group'),
        ),
        migrations.AddConstraint(
            model_name='addongroup',
            constraint=models.CheckConstraint(check=models.Q(('max_select__gte', models.F('min_select'))), name='addon_group_max_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='addongroup',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_addon_group_name_per_product'),
        ),
    ]
