# Generated by Django 4.2.26 on 2025-12-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboChoiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('min_select', models.PositiveIntegerField(default=0)),
                ('max_select', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('single', 'Single'), ('combo', 'Combo')], default='single', max_length=16),
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_combos', to='commerce.product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='ComboChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='commerce.combochoicegroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.product')),
            ],
        ),
        migrations.AddField(
            model_name='combochoicegroup',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_groups', to='commerce.product'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='combo_component_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('parent', 'component'), name='uniq_combo_component'),
        ),
        migrations.AddConstraint(
            model_name='combochoiceoption',
            constraint=models.CheckConstraint(check=models.Q(('price_delta__gte', 0)), name='combo_option_price_delta_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='combochoiceoption',
            constraint=models.UniqueConstraint(fields=('group', 'product'), name='uniq_combo_option_product_per_group'),
        ),
        migrations.AddIndex(
            model_name='combochoicegroup',
            index=models.Index(fields=['combo', 'sort_order'], name='commerce_co_combo_i_354a46_idx'),
        ),
        migrations.AddConstraint(
            model_name='combochoicegroup',
            constraint=models.CheckConstraint(check=models.Q(('max_select__gte', models.F('min_select'))), name='combo_group_max_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='combochoicegroup',
            constraint=models.UniqueConstraint(fields=('combo', 'name'), name='uniq_combo_group_name_per_combo'),
        ),
    ]
