# Generated by Django 4.2.26 on 2025-12-23 17:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_combochoicegroup_product_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemComboSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=120)),
                ('product_sku', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_selections', to='commerce.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemComboSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.combochoicegroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_selections', to='commerce.cartitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.combochoiceoption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderitemcomboselection',
            constraint=models.CheckConstraint(check=models.Q(('unit_price_delta__gte', 0)), name='order_combo_sel_price_delta_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitemcomboselection',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='order_combo_sel_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='cartitemcomboselection',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='cart_combo_sel_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='cartitemcomboselection',
            constraint=models.UniqueConstraint(fields=('item', 'option'), name='uniq_cart_combo_item_option'),
        ),
    ]
