# Generated by Django 4.2.26 on 2025-12-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_orderitemcomboselection_cartitemcomboselection_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='combochoiceoption',
            index=models.Index(fields=['group'], name='commerce_co_group_i_5b1ce9_idx'),
        ),
    ]
