# Generated by Django 4.2.5 on 2023-09-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restau', '0031_remove_produtosfidelizacao_fidelizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('unidade', models.FloatField(default=0.0, verbose_name='Unidade por Euro')),
                ('ementa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restau.ementa')),
            ],
            options={
                'verbose_name': 'Fidelidade',
                'verbose_name_plural': 'Fidelidades',
            },
        ),
        migrations.CreateModel(
            name='ProdutoFidelidadeIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pontos Recompensa')),
                ('pontos_para_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pontos para Oferta')),
                ('ementa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_fidelidade', to='restau.ementa')),
                ('fidelidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelidade.fidelidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restau.products')),
            ],
        ),
    ]
