# Generated by Django 4.2.5 on 2023-09-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0031_remove_produtosfidelizacao_fidelizacao_and_more'),
        ('fidelidade', '0003_alter_produtofidelidadeindividual_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtofidelidadeindividual',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restau.products', verbose_name='Produto'),
        ),
    ]
