# Generated by Django 4.2.5 on 2023-09-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0005_ofertasfidelidade_comprasfidelidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertasfidelidade',
            options={'verbose_name': 'Oferta Fidelidade', 'verbose_name_plural': 'Ofertas Fidelidade'},
        ),
    ]
