# Generated by Django 4.2.5 on 2023-09-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fidelidade', '0006_alter_ofertasfidelidade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasfidelidade',
            name='utilizador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
