# Generated by Django 4.2.5 on 2023-09-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0008_alter_ofertasfidelidade_utilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fidelidade',
            name='unidade',
        ),
        migrations.AddField(
            model_name='fidelidade',
            name='desconto',
            field=models.IntegerField(default=0, verbose_name='Desconto'),
        ),
    ]
