# Generated by Django 4.2.5 on 2023-09-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0009_remove_fidelidade_unidade_fidelidade_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtofidelidadeindividual',
            name='visibilidade',
            field=models.BooleanField(default=False, verbose_name='Visibilidade'),
        ),
    ]
