# Generated by Django 4.2.5 on 2023-09-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0010_produtofidelidadeindividual_visibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidelidade',
            name='desconto',
            field=models.IntegerField(verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='produtofidelidadeindividual',
            name='pontos_para_oferta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontos para Oferta'),
        ),
        migrations.AlterField(
            model_name='produtofidelidadeindividual',
            name='pontos_recompensa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontos Recompensa'),
        ),
    ]
