# Generated by Django 4.2.9 on 2024-02-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0015_alter_comprasfidelidade_pontos_adicionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasfidelidade',
            name='compra',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Compra'),
        ),
    ]
