# Generated by Django 4.2.10 on 2024-02-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0016_comprasfidelidade_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertasfidelidade',
            name='pontos_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pontos Gastos'),
        ),
    ]
