# Generated by Django 4.2.3 on 2024-02-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0019_respostafidelidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostafidelidade',
            name='utilizador',
        ),
    ]
