# Generated by Django 4.2.10 on 2024-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0020_remove_respostafidelidade_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasfidelidade',
            name='chave_g',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Chave G'),
        ),
    ]
