# Generated by Django 4.2.15 on 2024-08-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0021_comprasfidelidade_chave_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasfidelidade',
            name='expirado',
            field=models.BooleanField(default=False, verbose_name='Expirado'),
        ),
    ]
