# Generated by Django 4.2.15 on 2024-08-17 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0022_comprasfidelidade_expirado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertasfidelidade',
            name='processado',
            field=models.BooleanField(default=False, verbose_name='Processado'),
        ),
        migrations.AlterField(
            model_name='comprasfidelidade',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='ofertasfidelidade',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
    ]
