# Generated by Django 4.2.25 on 2025-11-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fidelidade', '0023_ofertasfidelidade_processado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO_RES', 'Resgate'), ('DEBITO_EXP', 'Expiração'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20)),
                ('pontos', models.DecimalField(decimal_places=3, max_digits=10)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_pontos', to='fidelidade.comprasfidelidade')),
                ('fidelidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_pontos', to='fidelidade.fidelidade')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_pontos', to='fidelidade.ofertasfidelidade')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_pontos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento de Pontos',
                'verbose_name_plural': 'Movimentos de Pontos',
                'indexes': [models.Index(fields=['utilizador', 'fidelidade', 'status'], name='fidelidade__utiliza_bab061_idx'), models.Index(fields=['utilizador', 'criado_em'], name='fidelidade__utiliza_ff9b6f_idx'), models.Index(fields=['tipo'], name='fidelidade__tipo_dcc109_idx')],
            },
        ),
    ]
