# Generated by Django 4.2.26 on 2025-11-15 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fidelidade', '0024_movimentopontos'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('birthday_minus_8', 'Aniversário -8 dias'), ('birthday_day', 'Aniversário - dia'), ('points_minus_15', 'Pontos -15 dias'), ('points_minus_7', 'Pontos -7 dia'), ('points_minus_1', 'Pontos -1 dia')], max_length=50)),
                ('referencia_data', models.DateField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tipo', 'referencia_data')},
            },
        ),
    ]
