# Generated by Django 4.2.27 on 2025-12-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0026_alter_comprasfidelidade_utilizador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasfidelidade',
            name='compra',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='comprasfidelidade',
            name='pontos_adicionados',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Pontos Adicionados'),
        ),
        migrations.AlterField(
            model_name='ofertasfidelidade',
            name='pontos_gastos',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pontos Gastos'),
        ),
    ]
