# Generated by Django 4.2.27 on 2026-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0027_alter_comprasfidelidade_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='code',
            field=models.SlugField(blank=True, help_text='Código único para a pergunta', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='respostas',
            name='value',
            field=models.SlugField(blank=True, help_text='Código único para a resposta', null=True),
        ),
    ]
