# Generated by Django 4.2.27 on 2026-01-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0028_perguntas_code_respostas_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntas',
            name='code',
            field=models.SlugField(help_text='Código único para a pergunta', unique=True),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='value',
            field=models.SlugField(help_text='Código único para a resposta'),
        ),
    ]
