# Generated by Django 4.2.27 on 2026-01-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0029_alter_perguntas_code_alter_respostas_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentopontos',
            name='code',
            field=models.CharField(blank=True, help_text='Código lógico do evento (ex: PROFILE_COMPLETED_BONUS)', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='movimentopontos',
            constraint=models.UniqueConstraint(fields=('utilizador', 'fidelidade', 'code'), name='uniq_user_fidelity_event_code'),
        ),
    ]
