# Generated by Django 4.2.19 on 2025-10-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_version', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'ordering': ['-data_lancamento']},
        ),
    ]
