# Generated by Django 4.2.19 on 2025-10-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_version', '0002_alter_appversion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'get_latest_by': 'data_lancamento', 'ordering': ['-data_lancamento']},
        ),
        migrations.AlterField(
            model_name='appversion',
            name='data_lancamento',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='sistema_operativo',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='appversion',
            constraint=models.UniqueConstraint(fields=('sistema_operativo', 'versao'), name='unique_appversion_os_version'),
        ),
    ]
