# Generated by Django 4.2.15 on 2024-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senhas',
            name='frase_pub',
            field=models.CharField(blank=True, help_text='Frase pública', max_length=200, null=True, verbose_name='Frase pública'),
        ),
    ]
