# Generated by Django 4.2.15 on 2024-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0002_senhas_frase_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrasePub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(help_text='Frase pública', max_length=150, verbose_name='Frase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='senhas',
            name='frase_pub',
        ),
    ]
