from django.urls import path
from restau.views import (                      # type: ignore
    index, admin_home, produtos, produto, criar_produto, atualizar_produto,
    apagar_produto, encomendas, categoria, criar_categoria,
    atualizar_categoria, apagar_categoria, subcategoria, criar_subcategoria,
    atualizar_subcategoria, apagar_subcategoria, ordenar_produtos, ementas,
    criar_ementa, atualizar_ementa, apagar_ementa, povoar_ementa, ementa,
    configuracao, Subcategorias, ordenar_subcategorias, categorias,
    ordenar_categorias, adicionar_foto, galeria, povoar_galeria, imagem_logo,
    criar_logo, apagar_logo, escolher_logo, imagem_topo, criar_imagem_topo,
    apagar_imagem_topo, escolher_imagem_topo, intro, criar_intro, apagar_intro,
    escolher_intro, intro_imagem, criar_intro_imagem, apagar_intro_imagem,
    escolher_intro_imagem, frase_cima, criar_frase_cima, apagar_frase_cima,
    escolher_frase_cima, imagem_frase_cima, criar_imagem_frase_cima,
    apagar_imagem_frase_cima, escolher_imagem_frase_cima, frase_central,
    criar_frase_central, apagar_frase_central, escolher_frase_central,
    frase_baixo, criar_frase_baixo, apagar_frase_baixo, escolher_frase_baixo,
    imagem_frase_baixo, criar_imagem_frase_baixo, apagar_imagem_frase_baixo,
    escolher_imagem_frase_baixo, imagem_padrao, criar_imagem_padrao,
    apagar_imagem_padrao, escolher_imagem_padrao, contatos_site,
    criar_contatos_site, editar_contatos_site, google_maps, criar_google_maps,
    editar_google_maps, horario, criar_horario, editar_horario,
    admin_utilizadores, admin_utilizador, compras_utilizador,
    ofertas_utilizador, movimentos, lista_produtos_api, detalhe_produtos_api,
    categoria_api_detalhe
)

# namespace
app_name = 'restau'

urlpatterns = [
    path('', index, name='index'),
    path('restau/pages/encomendas/', encomendas, name='encomendas'),
    path('restau/pages/admin_home/', admin_home, name='admin_home'),
    # product
    path('restau/pages/produtos/', produtos, name='produtos'),
    path('restau/pages/<int:produto_id>/', produto, name='produto'),
    path('restau/pages/criar_produto/',
         criar_produto, name='criar_produto'),
    path('restau/pages/<int:produto_id>/atualizar_produto/',
         atualizar_produto, name='atualizar_produto'),
    path('restau/pages/<int:produto_id>/apagar_produto/',
         apagar_produto, name='apagar_produto'),
    path('restau/pages/ordenar_produtos/',
         ordenar_produtos, name='ordenar_produtos'),
    # category
    path('restau/pages/categorias/', categorias, name='categorias'),
    path('restau/pages/categoria/<int:categoria_id>/',
         categoria, name='categoria'),
    path('restau/pages/criar_categoria/',
         criar_categoria, name='criar_categoria'),
    path('restau/pages/<int:categoria_id>/atualizar_categoria/',
         atualizar_categoria, name='atualizar_categoria'),
    path('restau/pages/<int:categoria_id>/apagar_categoria/',
         apagar_categoria, name='apagar_categoria'),
    path('restau/pages/ordenar_categorias/',
         ordenar_categorias, name='ordenar_categorias'),
    # subcategoria
    path('restau/pages/subcategorias/', Subcategorias, name='subcategorias'),
    path('restau/pages/subcategoria/<int:subcategoria_id>/',
         subcategoria, name='subcategoria'),
    path('restau/pages/criar_subcategoria/',
         criar_subcategoria, name='criar_subcategoria'),
    path('restau/pages/<int:subcategoria_id>/atualizar_subcategoria/',
         atualizar_subcategoria, name='atualizar_subcategoria'),
    path('restau/pages/<int:subcategoria_id>/apagar_subcategoria/',
         apagar_subcategoria, name='apagar_subcategoria'),
    path('restau/pages/ordenar_subcategorias/',
         ordenar_subcategorias, name='ordenar_subcategorias'),
    # Ementas
    path('restau/pages/criar_ementa/', criar_ementa, name='criar_ementa'),
    path('restau/pages/<int:ementa_id>/atualizar_ementa/',
         atualizar_ementa, name='atualizar_ementa'),
    path('restau/pages/<int:ementa_id>/apagar_ementa/',
         apagar_ementa, name='apagar_ementa'),
    path('restau/pages/ementa/<int:ementa_id>/',
         ementa, name='ementa'),
    path('restau/pages/ementas/', ementas, name='ementas'),
    path('restau/pages/povoar_ementa/<int:ementa_id>/',
         povoar_ementa, name='povoar_ementa'),
    # Configuração
    path('restau/pages/configuracao/', configuracao, name='configuracao'),
    # Galeria
    path('restau/pages/galeria/', galeria, name='galeria'),
    path('restau/pages/adicionar_foto/',
         adicionar_foto, name='adicionar_foto'),
    path('restau/pages/povoar_galeria/',
         povoar_galeria, name='povoar_galeria'),
    # ImagemLogo
    path('restau/pages/logos/', imagem_logo, name='imagem_logo'),
    path('restau/pages/criar_logo/', criar_logo, name='criar_logo'),
    path('restau/pages/apagar_logo/', apagar_logo, name='apagar_logo'),
    path('restau/pages/escolher_logo/', escolher_logo, name='escolher_logo'),
    # ImagemTopo
    path('restau/pages/imagem_topo/', imagem_topo, name='imagem_topo'),
    path('restau/pages/criar_imagem_topo/',
         criar_imagem_topo, name='criar_imagem_topo'),
    path('restau/pages/apagar_imagem_topo/',
         apagar_imagem_topo, name='apagar_imagem_topo'),
    path('restau/pages/escolher_imagem_topo/',
         escolher_imagem_topo, name='escolher_imagem_topo'),
    # Intro
    path('restau/pages/intro/', intro, name='intro'),
    path('restau/pages/criar_intro/',
         criar_intro, name='criar_intro'),
    path('restau/pages/apagar_intro/',
         apagar_intro, name='apagar_intro'),
    path('restau/pages/escolher_intro/',
         escolher_intro, name='escolher_intro'),
    # Intro Imagem
    path('restau/pages/intro_imagem/', intro_imagem, name='intro_imagem'),
    path('restau/pages/criar_intro_imagem/',
         criar_intro_imagem, name='criar_intro_imagem'),
    path('restau/pages/apagar_intro_imagem/',
         apagar_intro_imagem, name='apagar_intro_imagem'),
    path('restau/pages/escolher_intro_imagem/',
         escolher_intro_imagem, name='escolher_intro_imagem'),
    # Frase Cima
    path('restau/pages/frase_cima/', frase_cima, name='frase_cima'),
    path('restau/pages/criar_frase_cima/',
         criar_frase_cima, name='criar_frase_cima'),
    path('restau/pages/apagar_frase_cima/',
         apagar_frase_cima, name='apagar_frase_cima'),
    path('restau/pages/escolher_frase_cima/',
         escolher_frase_cima, name='escolher_frase_cima'),
    # Imagem Frase Cima
    path('restau/pages/imagem_frase_cima/',
         imagem_frase_cima, name='imagem_frase_cima'),
    path('restau/pages/criar_imagem_frase_cima/',
         criar_imagem_frase_cima, name='criar_imagem_frase_cima'),
    path('restau/pages/apagar_imagem_frase_cima/',
         apagar_imagem_frase_cima, name='apagar_imagem_frase_cima'),
    path('restau/pages/escolher_imagem_frase_cima/',
         escolher_imagem_frase_cima, name='escolher_imagem_frase_cima'),
    # Imagem Frase Central
    path('restau/pages/frase_central/',
         frase_central, name='frase_central'),
    path('restau/pages/criar_frase_central/',
         criar_frase_central, name='criar_frase_central'),
    path('restau/pages/apagar_frase_central/',
         apagar_frase_central, name='apagar_frase_central'),
    path('restau/pages/escolher_frase_central/',
         escolher_frase_central, name='escolher_frase_central'),
    # Frase baixo
    path('restau/pages/frase_baixo/',
         frase_baixo, name='frase_baixo'),
    path('restau/pages/criar_frase_baixo/',
         criar_frase_baixo, name='criar_frase_baixo'),
    path('restau/pages/apagar_frase_baixo/',
         apagar_frase_baixo, name='apagar_frase_baixo'),
    path('restau/pages/escolher_frase_baixo/',
         escolher_frase_baixo, name='escolher_frase_baixo'),
    # Imagem Frase baixo
    path('restau/pages/imagem_frase_baixo/',
         imagem_frase_baixo, name='imagem_frase_baixo'),
    path('restau/pages/criar_imagem_frase_baixo/',
         criar_imagem_frase_baixo, name='criar_imagem_frase_baixo'),
    path('restau/pages/apagar_imagem_frase_baixo/',
         apagar_imagem_frase_baixo, name='apagar_imagem_frase_baixo'),
    path('restau/pages/escolher_imagem_frase_baixo/',
         escolher_imagem_frase_baixo, name='escolher_imagem_frase_baixo'),
    # Imagem Padrao
    path('restau/pages/imagem_padrao/',
         imagem_padrao, name='imagem_padrao'),
    path('restau/pages/criar_imagem_padrao/',
         criar_imagem_padrao, name='criar_imagem_padrao'),
    path('restau/pages/apagar_imagem_padrao/',
         apagar_imagem_padrao, name='apagar_imagem_padrao'),
    path('restau/pages/escolher_imagem_padrao/',
         escolher_imagem_padrao, name='escolher_imagem_padrao'),
    # Contatos Site
    path('restau/pages/contatos_site/', contatos_site, name='contatos_site'),
    path('restau/pages/criar_contatos_site/',
         criar_contatos_site, name='criar_contatos_site'),
    path('restau/pages/editar_contatos_site/<int:contato_id>',
         editar_contatos_site, name='editar_contatos_site'),
    # Google Maps
    path('restau/pages/google_maps/', google_maps, name='google_maps'),
    path('restau/pages/criar_google_maps/',
         criar_google_maps, name='criar_google_maps'),
    path('restau/pages/editar_google_maps/<int:map_id>',
         editar_google_maps, name='editar_google_maps'),
    # Horário
    path('restau/pages/horario/', horario, name='horario'),
    path('restau/pages/criar_horario/',
         criar_horario, name='criar_horario'),
    path('restau/pages/editar_horario/<int:horario_id>',
         editar_horario, name='editar_horario'),
    # Admin-Utilizadores
    path('restau/pages/admin_utilizadores/',
         admin_utilizadores, name='admin_utilizadores'),
    path('restau/pages/admin_utilizador/<int:utilizador_pk>/',
         admin_utilizador, name='admin_utilizador'),
    path('restau/pages/compras_utilizador/<int:utilizador_id>/',
         compras_utilizador, name='compras_utilizador'),
    path('restau/pages/ofertas_utilizador/<int:utilizador_id>/',
         ofertas_utilizador, name='ofertas_utilizador'),
    path('restau/pages/movimentos/<int:utilizador_id>/',
         movimentos, name='movimentos'),

    # Produtos API
    path('produtos/api/v1/',
         lista_produtos_api, name='produtos_api_v1'),
    path('produtos/api/v1/<int:pk>/',
         detalhe_produtos_api, name='detalhe_produtos_api_v1'),
    path('produtos/api/v1/categoria/<int:pk>/',
         categoria_api_detalhe, name='produto_categoria_api_v1'),
]
